### ISSUE TITLE
Issue with opera browser : only one line displayed

### ISSUE THREAD

**Issue by polytan02** [shellinabox/shellinabox#315]
Hello,

I'm using shellinabox on my server. It works fine apart from accessing it via opera.

The bug is a bit weird : only a single line is displayed instead of using the entire full screen.

The issue has been documented here : https://code.google.com/p/shellinabox/issues/detail?id=63
but I couldn't understand how to modify vt100.jspp (I've never done jspp before :( )

**Comment by KLuka** [comment]
Hello, I tested latest shellinabox with Opera 30.0.1835.52 and it works fine for me...

What versions are you using? 

```
luka@ubuntu:~$ shellinaboxd --version
ShellInABox version 2.15 (revision b3309b2)
```

You can check shellinabox version with command above, or form context menu with right click and selecting "About" option.

**Comment by polytan02** [comment]
the packaged version for yunohost (yunohost.org) is 2.10 revision 239

**Comment by KLuka** [comment]
Ok, than that is it...

You can try to build new version from our repo, or maybe you can try to install our prebuilt [deb package v2.15-rc2](https://github.com/shellinabox/shellinabox/releases/tag/v2.15-rc2), if it fits on your system. It should fix your problem.

I will close this issue because it is already solved. But if you have any more question just post them here :wink:

**Comment by polytan02** [comment]
Hi,

I removed the old shellinabox.deb (the one from debian servers) and installed the git version following the guide on main depot page.
Now I have version 2.15 for amd64 (rev 4f9c682).

The problem is still there for me, only one line available.

**Comment by KLuka** [comment]
Ohh... Is it possible that your browser has some js files cached? Can you try to delete cached files or refresh the page with Ctrl+F5... 

If this is not the case I will have to investigate further and try to reproduce the problem on my build. What version of Opera browser are you using?

**Comment by polytan02** [comment]
If you want, I can have a temporary access available for you on my test server so that you can test your opera and see the issue ?

**Comment by KLuka** [comment]
Ok you can give me the access.

**Comment by polytan02** [comment]
Do you have an email address ? I cannot find any private discussions within github.

Otherwise, I'm on freenode right now. Do you have a nickname there ?

**Comment by KLuka** [comment]
Can you try to find me as KLuka. I am not so familiar with freenode. Is it ok if I use web application?

**Comment by polytan02** [comment]
No problem.

If you are on freenode, can you join the channel #shellinabox ?

the command is /j #shellinabox

**Comment by KLuka** [comment]
With help from @polytan02 I managed to reproduce and find a bug.

Bug is reproducible on latest Opera and Chrome browsers. You just need to play around with different zoom (ctrl +/-), browser window width and reloading the page.

The problem is that variable `this.isEmbedded` in vt100.jspp initializes to true, but it shouldn't. This happens because, in [this](https://github.com/shellinabox/shellinabox/blob/master/shellinabox/vt100.jspp#L990-L995) part of code, `window.innerWidth` in different from `this.container.offsetWidth` just in some cases. The difference is only by 1 pixel, maybe because of some rounding errors, IDK.

I need to think about how we should fix this. My first tough was to allow 1px difference, I just have to test this in situations when shellinabox is actually embedded... If anyone has a better ideas please feel free to share them :smile:

**Comment by polytan02** [comment]
Lastest patch solved the issue.

Thanks for the support :)
